### ISSUE TITLE
Install error - building wheel for pyliblio

### ISSUE THREAD

**Issue by braindie2020** [ideoforms/pylive#18]
Hi,

tried to instal pylive from PyPi and Git. There is a problem and I can see the the problem but have no idea to solve it.
After reading several threads in forums maybe it is a problem with python and anaconda.
Maybe anyone can help me thanks.
Thanks
System: macOS 

My error code via Papi:
  Building wheel for pyliblo (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /Users/.../opt/anaconda3/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/55/mk296wh53bj1bp16q350ltym0000gn/T/pip-install-s5m09wqy/pyliblo/setup.py'"'"'; __file__='"'"'/private/var/folders/55/mk296wh53bj1bp16q350ltym0000gn/T/pip-install-s5m09wqy/pyliblo/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/55/mk296wh53bj1bp16q350ltym0000gn/T/pip-wheel-ti67mhdy
       cwd: /private/var/folders/55/mk296wh53bj1bp16q350ltym0000gn/T/pip-install-s5m09wqy/pyliblo/
  Complete output (16 lines):
  running bdist_wheel
  running build
  running build_ext
  cythoning src/liblo.pyx to src/liblo.c
  /Users/.../opt/anaconda3/lib/python3.8/site-packages/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /private/var/folders/55/mk296wh53bj1bp16q350ltym0000gn/T/pip-install-s5m09wqy/pyliblo/src/liblo.pxd
    tree = Parsing.p_module(s, pxd, full_module_name)
  building 'liblo' extension
  creating build
  creating build/temp.macosx-10.9-x86_64-3.8
  creating build/temp.macosx-10.9-x86_64-3.8/src
  gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/.../opt/anaconda3/include -arch x86_64 -I/Users/.../opt/anaconda3/include -arch x86_64 -I/Users/.../opt/anaconda3/include/python3.8 -c src/liblo.c -o build/temp.macosx-10.9-x86_64-3.8/src/liblo.o -fno-strict-aliasing -Werror-implicit-function-declaration -Wfatal-errors
  src/liblo.c:611:10: fatal error: 'lo/lo.h' file not found
  #include "lo/lo.h"
           ^~~~~~~~~
  1 error generated.
  error: command 'gcc' failed with exit status 1

  ERROR: Failed building wheel for pyliblo

My error code from git

Installed /Users/.../opt/anaconda3/lib/python3.8/site-packages/pylive-0.2.1-py3.8.egg
Processing dependencies for pylive==0.2.1
Searching for pyliblo>=0.9.1
Reading https://pypi.org/simple/pyliblo/
Downloading https://files.pythonhosted.org/packages/c0/da/4b8052ab5aa07952d7fe7b068d737a042e76373573eadd340f7550eddea9/pyliblo-0.10.0.tar.gz#sha256=fc67f1950b827272b00f9f0dc4ed7113c0ccef0c1c09e9976dead40ebbf1798f
Best match: pyliblo 0.10.0
Processing pyliblo-0.10.0.tar.gz
Writing /var/folders/55/mk296wh53bj1bp16q350ltym0000gn/T/easy_install-p15f9dqw/pyliblo-0.10.0/setup.cfg
Running pyliblo-0.10.0/setup.py -q bdist_egg --dist-dir /var/folders/55/mk296wh53bj1bp16q350ltym0000gn/T/easy_install-p15f9dqw/pyliblo-0.10.0/egg-dist-tmp-unake4i4
no previously-included directories found matching 'doc/build'
/Users/.../opt/anaconda3/lib/python3.8/site-packages/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /private/var/folders/55/mk296wh53bj1bp16q350ltym0000gn/T/easy_install-p15f9dqw/pyliblo-0.10.0/src/liblo.pxd
  tree = Parsing.p_module(s, pxd, full_module_name)
src/liblo.c:611:10: fatal error: 'lo/lo.h' file not found
#include "lo/lo.h"

**Comment by ideoforms** [comment]
It looks like you haven't installed `liblo`, which is a required library for OSC support.
Install Homebrew, and then run `brew install liblo`, then retry the installation again.
Check the [README](https://github.com/ideoforms/pylive) for details.

If you still have problems, feel free to reopen this ticket.
