### ISSUE TITLE
LiveOSC Listeners?

### ISSUE THREAD

**Issue by mark-zarandi** [ideoforms/pylive#25]
I'm making a tool for myself and want to make sure I keep cpu usage down.  Is there an example of using pylive with LISTENERS or do i just query the set on each beat like in the clip-walk example to get the set.time?

**Comment by ideoforms** [comment]
Just coming back to this package and updating it for a new release in conjunction with [AbletonOSC](https://github.com/ideoforms/AbletonOSC) for Live 11+. Can you clarify the question and give an example of what you're trying to achieve?

**Comment by mark-zarandi** [comment]
I ended up just writing my own remote midi script in ableton instead.
