### ISSUE TITLE
Issues with AbletonOSC Compatibility 

### ISSUE THREAD

**Issue by shakfu** [ideoforms/pylive#34]
Just fyi, I initially tried to use the pylive version installed via pip with [AbletonOSC](https://github.com/ideoforms/AbletonOSC).

For the pip installed version of pylive, I thought it was a matter of simply changing the ports from 9000 and 9001 to the corresponding ones (AbletonOSC uses 11000 and 11001) but this was not successful.

I then tried the most recent (as of this post) code off of git, and it worked for me after a restart.

**Comment by ideoforms** [comment]
Thanks @shakfu, this is a good reminder for me to publish the latest to pypi - I’ll do that this weekend so that pip install can be used successfully again. 

Cheers!

**Comment by ideoforms** [comment]
@shakfu I have now pushed an updated version of pylive (v0.3.0) to pypi, so the latest pip version should work OK with AbletonOSC and Live 11.

**Comment by shakfu** [comment]
Thants great. 👍  Thanks for letting me know
