### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by standerksen** [ideoforms/pylive#5]
Using Python 2.7.14 on Windows 10, Ableton 9.5, running `python setup.py install` and getting:
```
cl : Command line error D8021 : invalid numeric argument '/Werror-implicit-function-declaration'
error: Setup script exited with error: command 'C:\\Users\\myusername\\AppData\\Local\\Programs\\Common\\Microsoft\\Visual C++ for Python\\9.0\\VC\\Bin\\cl.exe' failed with exit status 2
```

**Edit:** I've got it working after a tedious manual installation of `pyliblo`. However, now it cannot find my LiveOSC. I've tried both LiveOSC and LiveOSC2. Getting `timed out waiting for server response` on `set.scan()` in `ex-clip-walk.py`. Do I need to do anything else after selecting LiveOSC(2) as Control Surface in Ableton?

**Comment by ideoforms** [comment]
Unfortunately, changes in Live meant that LiveOSC was no longer compatible.
I've created a fork of LiveOSC which does work with Live 9.6/10:

https://github.com/ideoforms/LiveOSC

Select this as a control surface and it should work out of the box.

**Comment by standerksen** [comment]
@tildebyte I'm sorry, of has been a while so I cannot remember. I did not end up using this version of pylive afaik.

**Comment by tildebyte** [comment]
@standerksen; Hey, no worries; I just thought I'd ask :)

**Comment by standerksen** [comment]
@tildebyte I think I built it from source on a UNIX based OS. So not sure if it's going to work on Windows.

**Comment by ideoforms** [comment]
Thanks for the feedback. I'll add an issue to look at replacing liblo with python-osc or oscpy, which are pure-Python implementations. My main concern would be in performance, as I know that liblo can handle large volumes of traffic and would need to verify that they can do the same.

Let me know if you have any success with liblo as I can add it to the readme.

**Comment by tildebyte** [comment]
@ideoforms - THAT WOULD ROCK. I *really* would like to try out pylive, particularly in conjunction with isobar, but I switched over to windows a little while ago, and haven't looked back, so the easy answer of "try it on a Mac" doesn't apply.

That said, this has been the worst software build nightmare I've encountered in a while. Nothing I do works right the first time, and so far I've only managed to hand-hack liblo and pyliblo - I still can't get the whole thing working...

**Comment by tildebyte** [comment]
EDIT: just woolgathering here, I don't know how hard it would be, but maybe one of the other python OSC libs could be a drop-in replacement for py/liblo with a bit of tweaking? Then users would have a choice.

**Comment by ideoforms** [comment]
Hmm, where does the build problem lie?
It does look like liblo is actively maintained with Windows support:
https://github.com/radarsat1/liblo
Might be worth speaking to the maintainer?

On the other hand, pyliblo hasn't been touched for a few years so that may have fallen out of sync.

**Comment by tildebyte** [comment]
I somehow managed to get `liblo` to build successfully using MSYS2, but regardless of the options I used, I couldn't get a DLL.

The `pyliblo` build process is *nowhere near* as simple as indicated, and in any case, `pyliblo` only seems to want to use the `liblo` which **it** builds anyway, so trying to build it oneself is pointless.

The major problem in all of this AFAICT is that `pyliblo` wants to build `liblo` using an outdated Visual Studio which I can't find for download anywhere.

Disclaimer; I know next to nothing about Visual Studio and its build procedures.

**Comment by jayknowstheway** [comment]
ModuleNotFoundError: No module named 'Cython'

**Comment by jayknowstheway** [comment]
Running setup.py install for pyliblo ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/local/opt/python/bin/python3.7 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/ph/m_k6dbcs4sz9bz8pxxkydkpm0000py/T/pip-install-be0p8yp1/pyliblo/setup.py'"'"'; __file__='"'"'/private/var/folders/ph/m_k6dbcs4sz9bz8pxxkydkpm0000py/T/pip-install-be0p8yp1/pyliblo/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/ph/m_k6dbcs4sz9bz8pxxkydkpm0000py/T/pip-record-fuaddtsq/install-record.txt --single-version-externally-managed --compile
         cwd: /private/var/folders/ph/m_k6dbcs4sz9bz8pxxkydkpm0000py/T/pip-install-be0p8yp1/pyliblo/
    Complete output (14 lines):
    running install
    running build
    running build_ext
    skipping 'src/liblo.c' Cython extension (up-to-date)
    building 'liblo' extension
    creating build
    creating build/temp.macosx-10.13-x86_64-3.7
    creating build/temp.macosx-10.13-x86_64-3.7/src
    clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers -I/usr/local/include -I/usr/local/opt/openssl@1.1/include -I/usr/local/opt/sqlite/include -I/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/include/python3.7m -c src/liblo.c -o build/temp.macosx-10.13-x86_64-3.7/src/liblo.o -fno-strict-aliasing -Werror-implicit-function-declaration -Wfatal-errors
    src/liblo.c:599:10: fatal error: 'lo/lo.h' file not found
    #include "lo/lo.h"
             ^~~~~~~~~
    1 error generated.
    error: command 'clang' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/local/opt/python/bin/python3.7 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/ph/m_k6dbcs4sz9bz8pxxkydkpm0000py/T/pip-install-be0p8yp1/pyliblo/setup.py'"'"'; __file__='"'"'/private/var/folders/ph/m_k6dbcs4sz9bz8pxxkydkpm0000py/T/pip-install-be0p8yp1/pyliblo/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/ph/m_k6dbcs4sz9bz8pxxkydkpm0000py/T/pip-record-fuaddtsq/install-record.txt --single-version-externally-managed --compile Check the logs for full command output.
