### ISSUE TITLE
MIDI file to CLIP?

### ISSUE THREAD

**Issue by styk-tv** [ideoforms/pylive#7]
You mentioned in Readme a solid Midi library [mido](https://mido.readthedocs.io/en/latest/). Is there any chance you could at least provide a hint on how to take few bars of a midi file and turn it into a midi clip?

**Comment by ideoforms** [comment]
@styk-tv I've spent some time looking into this and have now added some exploratory features which allow you to add and query notes in a `Clip`:

[add_note](https://github.com/ideoforms/pylive/blob/master/live/clip.py#L154)

Give it a spin and let me know how you get on. 
Will next look at deleting notes, and improving robustness of `get_notes` (which will need a refactor of OSC bundle handling)

**Comment by styk-tv** [comment]
```
        self.clip.add_note(60, 0, 0.25, 60)
        self.clip.add_note(60, 1, 0.25, 10)
        self.clip.add_note(60, 2, 0.25, 120)
        self.clip.add_note(61, 3, 1, 120)
```

<img width="601" alt="Screenshot 2019-05-31 at 03 02 16" src="https://user-images.githubusercontent.com/838921/58676545-8ac06e00-8350-11e9-80fb-2b10605bd2d8.png">

seems to be working fine. thanks,
